# Unique name for this workflow
name: CI on PR

# Definition when the workflow should run
on:
    workflow_dispatch:
    pull_request:
        types: [opened, edited, synchronize, reopened]
        branches-ignore:
            - uat
            - main

# Jobs to be executed
jobs:
    lint-code:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@v3
            with:
              distribution: 'temurin'
              java-version: '11'
          - uses: pmd/pmd-github-action@v1
            id: pmd
            with:
              version: '6.40.0'
              sourcePath: 'force-app'
              rulesets: 'apex-ruleset.xml'
          - name: Fail build if there are violations
            if: steps.pmd.outputs.violations != 0
            run: exit 1
    scratch-org-test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          # Setup .npmrc file to publish to npm
          - uses: actions/setup-node@v3
            with:
              node-version: '16.x'
              registry-url: 'https://registry.npmjs.org'
          # Install Salesforce CLI
          - name: 'Install Salesforce CLI'
            run: |
              npm install sfdx-cli --location=global
              nodeInstallPath=$(npm config get prefix)
              echo "$nodeInstallPath/bin" >> $GITHUB_PATH
              sfdx --version