# Unique name for this workflow
name: CI on PR

# Definition when the workflow should run
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches-ignore:
      - uat
      - main
  workflow_dispatch:

# Jobs to be executed
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run plugins:install @salesforce/sfdx-scanner
      - name: Run SFDX Scanner - Report findings as comments
        uses: mitchspano/sfdx-scan-pull-request@v0.1.7
        with:
          pmdconfig: apex_ruleset.xml
          severity-threshold: 3
          strictly-enforced-rules: '[{ "engine": "pmd", "category": "Design,Best Practices,Code Style,Documentation,Error Prone,Performance,Security", "rule": "EmptyCatchBlock" }]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  scratch-org-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: |
          npm install sfdx-cli --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
          sfdx --version